server:
  port: 8084

spring:
  data:
    mongodb:
      uri: mongodb+srv://sweeti:sweeti123%23@cluster0.ildy9.mongodb.net
      database: microservices
      
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka